config/routes.rb
Rails.application.routes.draw do
  resources :boards
  resources :steps

  root to: "boards#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :tasks, dependent: :destroy
  accepts_nested_attributes_for :tasks, allow_destroy: true

  validates :name, presence: true
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :task

  validates :name, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :board
  has_many :steps, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to boards_path, notice: 'Board salvo com sucesso.' }
        format.json { render :index, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to boards_path, notice: 'Board salvo com sucesso.' }
        format.json { render :index, status: :created, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board deletada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:name, tasks_attributes: [:id, :name, :description, :_destroy])
    end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_step, only: [:edit, :update, :destroy]

  # GET /steps/new
  def new
    @step = Step.new(task_id: params[:task_id].to_i)
    respond_to do |format|
      format.js { render 'new.js.erb' }
    end
  end

  # GET /steps/1/edit
  def edit
    respond_to do |format|
      format.js { render 'edit.js.erb' }
    end
  end

  # POST /steps
  # POST /steps.json
  def create
    @step = Step.new(step_params)

    respond_to do |format|
      if @step.save
        @steps = Step.where(task_id: @step.task_id).order(:id)
        format.html { redirect_to edit_board_path(@step.task.board_id) }
        format.js {}
        format.json { render :show, status: :created, location: @step }
      else
        format.html { redirect_to root_path }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /steps/1
  # PATCH/PUT /steps/1.json
  def update
    respond_to do |format|
      if @step.update(step_params)
        format.html { redirect_to @step, notice: 'steps was successfully updated.' }
        format.js {}
        format.json { render :show, status: :ok, location: @step }
      else
        format.html { render :edit }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /steps/1
  # DELETE /steps/1.json
  def destroy
    @step.destroy
    respond_to do |format|
      @steps = Step.where(task_id: @step.task_id).order(:id)
      format.html { redirect_to steps_url, notice: 'steps was successfully destroyed.' }
      format.js {}
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_step
    @step = Step.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def step_params
    params.require(:step).permit(:task_id, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/boards/_form.html.erb
<%= nested_form_for board, :html => {:id => "board_create", :role => "form"} do |f| %>
  <div id="error_explanation">
    <ul>
      <% board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>

  <div class="form-inline form-group">
    <div class="form-group col-3">
      <%= h f.text_field :name, class: 'form-control col-12',
                         placeholder: "Digite o Nome", label: "Nome" %>
    </div>
    <button type="submit" class="btn btn-success col-auto" style="margin-right: 5px;">Salvar</button>

    <%= f.link_to_add :tasks,
                      data: {target: '#tasks'},
                      class: 'btn btn-primary col-auto',
                      style: "margin-right: 5px;" do %>
      <span class="fa fa-plus"></span> Adicionar Task
    <% end %>

    <% if f.object.tasks.blank? %>
      <%= link_to 'Voltar', boards_path, class: "btn btn-secondary col-auto" %>
    <% end %>
  </div>

  <%= render 'tasks/form', f: f %>

  <% if f.object.tasks.present? %>
    <div class="form-group col-md-12">
      <div class="form-row">
        <div class="col-2">
          <%= link_to 'Voltar', boards_path, class: "btn btn-secondary" %>
        </div>
        <div class="col-10">
          <button type="submit" class="btn btn-success float-right">Salvar</button>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

<div id="modal-step" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content" id="modal-content-step"></div>
  </div>
</div>

app/views/boards/edit.html.erb
<%= render 'form', board: @board %>

app/views/boards/index.html.erb
<div class="card border-dark">
  <div class="card-header">
    Boards

    <div class="actions-header">
      <%= link_to 'Nova Board', new_board_path, class: "btn btn-success btn-sm" %>
    </div>
  </div>
  <div class="card-body text-dark">
    <p id="notice"><%= notice %></p>
    <div class="table-step">
      <table class="table table-striped">
        <thead>
        <tr>
          <th scope="col">#</th>
          <th>Name</th>
          <th>Ações</th>
        </tr>
        </thead>
        <tbody>
        <% @boards.each do |board| %>
          <tr>
            <td><%= board.id %></td>
            <td><%= board.name %></td>
            <td>
              <%= link_to 'Editar', edit_board_path(board), class: "btn btn-warning btn-sm", title: "Editar Board" %>
              <%= link_to 'Deletar', board, class: "btn btn-danger btn-sm", title: "Deletar Board",
                          method: :delete, data: {confirm: 'Você tem certeza?'} %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/boards/new.html.erb
<%= render 'form', board: @board %>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @board.name %>
</p>

<%= link_to 'Edit', edit_board_path(@board) %> |
<%= link_to 'Back', boards_path %>

app/views/layouts/_menu_topo.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow fixed-top">
    <a class="navbar-brand" href="#">IBC Todo List</a>
</nav>

app/views/layouts/application.html.erb
<style>
  body, html{
    min-height: 75rem;
    padding-top: 3rem;
  }
</style>

<!DOCTYPE html>
<html>
<head>
  <title>IbcTodoList</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_pack_tag 'styles', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render 'layouts/menu_topo' %>
<div class="container">
  <div class="page-header" role="main">
    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/steps/_form.html.erb
<%= bootstrap_form_for @step, html: {id: "form_step_#{@step.task_id}", remote: true} do |f| %>
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">x</button>
    <h4 class="modal-title" id="myModalLabel">Inserir Step</h4>
  </div>
  <div class="modal-body">
    <%= f.hidden_field :task_id %>
    <div class="row">
      <div class="col-md-12">
        <%= h f.text_field :name, class: 'form-control',
                           label: 'Nome',
                           placeholder: "Digite o nome" %>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-white pull-left" data-dismiss="modal">Fechar</button>
    <%= f.submit "Salvar", class: 'btn btn-primary', remote: true, data: {disable_with: "Salvando..."} do %>
      <i class="fa fa-save"></i>
    <% end %>
  </div>
<% end %>

app/views/steps/_tbody_table_step.html.erb
<% steps.each do |step| %>
  <tr id="tr_step_<%= step.id %>">
   <%= render 'steps/tr_table_step', step: step %>
  </tr>
<% end %>

app/views/steps/_tr_table_step.html.erb
<td><%= h step.id %> </td>
<td><%= h step.name %> </td>
<td>
  <%= link_to edit_step_path(step),
              {remote: true, 'data-toggle' => "modal", 'data-target' => '#modal-window',
               class: 'btn btn-warning btn-sm'} do %>
    <i class="fa fa-thumbs-o-down"></i> Editar
  <% end %>
  <%= link_to 'Deletar', step, class: "btn btn-danger btn-sm", title: "Deletar Board",
              method: :delete, data: {confirm: 'Você tem certeza?'}, remote: true %>
</td>

app/views/steps/create.js.erb
$('#modal-step').modal('hide');
$("#modal-content-step").html("");

$('#tbody_step_<%= @step.task_id %>').html("<%= j(render('steps/tbody_table_step', steps: @steps)) %>");

app/views/steps/destroy.js.erb
$('#tbody_step_<%= @step.task_id %>').html("<%= j(render('steps/tbody_table_step', steps: @steps)) %>");

app/views/steps/edit.js.erb
$("#modal-step").modal();
$("#modal-content-step").html("<%= j (render 'steps/form') %>");

app/views/steps/new.js.erb
$("#modal-step").modal();
$("#modal-content-step").html("<%= j (render 'steps/form') %>");

app/views/steps/update.js.erb
$('#modal-step').modal('hide');
$("#modal-content-step").html("");

$('#tr_step_<%= @step.id %>').html("<%= j(render('steps/tr_table_step', step: @step)) %>");

app/views/tasks/_form.html.erb
<div id="tasks">
  <%= f.fields_for :tasks do |ff| %>
    <div class="form-group col-md-12">
      <div class="card border-dark">
        <div class="card-header">
          Editar Task
        </div>
        <div class="card-body text-dark">

          <div class="form-group">
            <%= h ff.text_field :name, class: 'form-control', placeholder: "Digite o Nome", label: "Nome" %>
          </div>

          <div class="form-group">
            <%= h ff.text_area :description, :rows => 5, :class => 'form-control', :label => "Descrição",
                               :placeholder => "Digite a descrição", :label_col => "col-sm-2", :control_col => "col-sm-10" %>

          </div>

          <% unless ff.object.new_record? %>
            <div class="form-group">
              <%= link_to new_step_path(task_id: ff.object.id),
                          {:remote => true, 'data-toggle' => "modal", 'data-target' => '#modal-window',
                           class: 'btn btn-primary btn-md'} do %>
                <i class="fa fa-thumbs-o-down"></i> Inserir Step
              <% end %>
            </div>

            <div class="form-group">
              <div class="table-step">
                <table class="table table-striped">
                  <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Step</th>
                    <th scope="col">Ações</th>
                  </tr>
                  </thead>
                  <tbody id="tbody_step_<%= ff.object.id %>">
                  <%= render 'steps/tbody_table_step', steps: ff.object.steps %>
                  </tbody>
                </table>
              </div>
            </div>
          <% end %>
        </div>

        <div class="card-footer text-dark">
          <div class="form-group">
            <%= ff.link_to_remove class: 'btn btn-danger btn-sm' do %>
              <i class="fa fa-trash-o"></i> Remover Task
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Board</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.board %></td>
        <td><%= task.name %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Board:</strong>
  <%= @task.board %>
</p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>